boostorg/process

include/boost/process/detail/windows/search_path.hpp

Original code checks for "program", "program.exe", "program.exe.com" and "program.exe.com.bat" instead of "program", "program.exe", "program.com" and "program.bat".
This change fixes this.

Fix extension adding in "search_path" (Windows)

---

include/boost/process/detail/config.hpp

In order to build boost::process::child() with Xcode, this change provides an alternative overloading of boost::process::detail::throw_last_error().
For example I got the following compilation error against Boost 1.64.0 with Xcode 5.1.1, 6.2, 7.2.1, and 8.3.2 consistently (under -std=c++11):
> In file included from ../../../src/gui/view-frame.cc:6:
> In file included from ../../../src/gui/view-frame.h:8:
> In file included from /Users/abe/src/Flint/xcode/usr/include/boost/process/child.hpp:21:
> In file included from /Users/abe/src/Flint/xcode/usr/include/boost/process/detail/child_decl.hpp:29:
> /Users/abe/src/Flint/xcode/usr/include/boost/process/detail/posix/terminate.hpp:26:9: error: no matching function for call to 'throw_last_error'
> …

Overloading boost::process::detail::throw_last_error() for Xcode's clang++

---

include/boost/process/detail/windows/basic_cmd.hpp
test/wargs_cmd.cpp

I independently stumbled across the unquoted wargs with spaces bug, and while fixing it, also found that the wargs unit test was 1/2 disabled. I discarded my fix and pulled from https://github.com/klemens-morgenstern/boost-process, then removed the return statements -- that's why both changes show up in this PR.

Restore wargs tests

---

include/boost/process/detail/posix/wait_for_exit.hpp

This is making the library a little nicer. Consider this example:
// child.cpp
int main()
{
throw 0;
}
// parent.cpp
#include <boost/process.hpp>
int main()
{
boost::process::child("./child").wait();
}`
In the current state, this will output the following:
% ./parent
libc++abi.dylib: terminating with uncaught exception of type int
libc++abi.dylib: terminating with uncaught exception of type boost::process::process_error: waitpid(2) failed: No child processes
zsh: abort      ./parent`
With this patch, you get this output instead
% ./parent
libc++abi.dylib: terminating with uncaught exception of type int
libc++abi.dylib: terminating with uncaught exception of type boost::process::process_error: process terminated due to receipt of a signal
zsh: abort      ./parent`
I want to point out again …

Respect WIFSIGNALED

---

include/boost/process/detail/child_decl.hpp
include/boost/process/detail/posix/basic_pipe.hpp

Valgrind complains about:
==18274== Conditional jump or move depends on uninitialised value(s)
==18274==    at 0x4E63291: boost::process::child::_exited() (child_decl.hpp:54)
==18274==    by 0x4E634B0: boost::process::child::~child() (child_decl.hpp:93)
==18274==  Uninitialised value was created by a stack allocation
==18274==    at 0x4E6351A: boost::process::child::running() (child_decl.hpp:102)
Line numbers refer to ver 1.65.1
Not sure what should be a proper fix for this. Initialize "code" as -1 for now.
Valgrind also complains about close(-1) in basic_pipe.hpp. Should not close if _sink or _source is -1.

fix uninitialized variable and close(-1) behavior

---

include/boost/process/detail/child_decl.hpp

_terminate field is now copied from the move assingment operator on
child. This fixes the issue that a child process could previously only
be terminated() once (even after reassignment).

Fix move assignment for child_decl

---

include/boost/process/detail/child_decl.hpp

I started to use clang-tidy on my project and it detected the use of an uninitialized variable.
I'm not sure if the changes I've done are really the solution, but it at least does change undefined behavior into exit_code = 0.
This is a minimal example to see the clang-tidy warning:
test.cpp:
```
#include <boost/process.hpp>
int main() { boost::process::child proc{"prog"}; }
```
clang-tidy call:
```
$ git clone --recursive https://github.com/boostorg/boost
$ clang-tidy -checks=clang-analyzer-core.CallAndMessage test.cpp -- clang++ --std=c++14 -I boost/libs/process/include/ -I boost/libs/config/include/ -I boost/libs/system/include/ -I boost/libs/filesystem/include/ -I boost/libs/core/include/ -I boost/libs/type_traits/include/ -I boost/libs/predef/include/ -I boost/libs/assert/include/ -I …
```

fix use of uninitalized variable

---

include/boost/process/detail/windows/job_workaround.hpp

WINAPI macro definition in Boost.WinAPI is deprecated as it may clash with the macro defined in Windows SDK.

Switch WINAPI calling convention macros to the replacements from Boost.WinAPI

---

include/boost/process/detail/posix/is_running.hpp

The use of the WIFSTOPPED bits did not go far enough on Solaris. It
is expected to also have a non-zero value in the next bytes. This
new value is tested be valid on Linux, MacOS and Solaris.
Fixes #51

Changes still_active constant to support Solaris.

---

doc/extend.qbk
doc/tutorial.qbk

In an example `boost::asio::io_service ios;` is used like this and looks in the generated doc like `boost::asio::boost::asio::io_service ios;` This pull request removes `boost::asio::` from the example.

removes boost::asio:: from example in doc

---

include/boost/process/detail/posix/io_context_ref.hpp
include/boost/process/detail/posix/on_exit.hpp

In file included from /home/ldco/boost/include/boost/process/detail/on_exit.hpp:12:0,
from /home/ldco/boost/include/boost/process/async.hpp:33,
from /home/ldco/boost/include/boost/process.hpp:23,
from /home/ldco/Projects/Teaching/Teaching/Boost/Process/Process1/src/main.cpp:7:
/home/ldco/boost/include/boost/process/detail/posix/on_exit.hpp:30:6: warning: extra ‘;’ [-Wpedantic]
};
^
In file included from /home/ldco/boost/include/boost/process/async.hpp:42:0,
from /home/ldco/boost/include/boost/process.hpp:23,
from /home/ldco/Projects/Teaching/Teaching/Boost/Process/Process1/src/main.cpp:7:
/home/ldco/boost/include/boost/process/detail/posix/io_context_ref.hpp:67:6: warning: extra ‘;’ [-Wpedantic]
};
^

fix warning due to extra semi colon

---

include/boost/process/environment.hpp

warning: moving a local object in a return statement prevents copy elision

Fix GCC9 warning

---

include/boost/process/detail/posix/basic_pipe.hpp

Based on the code from executor.hpp, a signal can cause invoking a child process to fail because reading/writing the pipe was interrupted.

Guard against EINTR in basic_pipe

---

include/boost/process/detail/windows/search_path.hpp

Hi Boost Process maintainers,
while compiling under windows, I faced a C4456 warning in boost::process::detail::windows::search_path
( https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4456 ) as declaration of 'pp' hides previous local declaration. 
In order to fix this warning, I renamed the internal variable inside the for loop.
As we are compiling with "treat warning as error", we require this fix to be available in future releases of boost::process. 
Thanks for considering and best regards
Michael

fixed hidden local variable

---

include/boost/process/detail/posix/environment.hpp
test/async_pipe.cpp
test/environment.cpp

Notably, directly assigning a `wnative_environment` to a `native_environment` now works with POSIX environments. Previously, it failed to compile.

Miscellaneous fixes related to POSIX environments

---

include/boost/process/detail/windows/basic_cmd.hpp

Fix double quotes processing on Windows:
- quotes should only be added when not already present
- quotes need to be used when an argument includes spaces or double quotes
- quotes inside an argument should be doubled (that's the way Windows does escaping)
Test:
`BOOST_ASSERT(bp::detail::windows::build_args("echo", {"\"1\"", "2 3", "4\"5", "6 \"7"}) == "echo \"1\" \"2 3\" \"4\"\"5\" \"6 \"\"7\"");
`

Fix double quotes processing on Windows

---

include/boost/process/pipe.hpp

The child process may exit at any time.
When the child process is existed, writing to pipe may failed.
In this case pptr is still pointing to the same address as epptr, which should not be written.
It causes the heap corrupted.
add these code before include boost headers:
```
std::mutex m;
std::set<intptr_t> mems;
void* operator new(std::size_t n)
{
if (n == 1024)
{
auto p = VirtualAlloc(nullptr, 8192, MEM_RESERVE, PAGE_READWRITE);
auto r = VirtualAlloc(p, 4096, MEM_COMMIT, PAGE_READWRITE);
auto x = (void*)((char*)p + 1024 * 3);
std::stringstream ss;
ss << "1024 byte from " << x << std::endl;
OutputDebugStringA(ss.str().c_str());
std::unique_lock<std::mutex> lg(m);
mems.insert((intptr_t)x);
return x;
}
else
{
return malloc(n);
}
}
void operator delete(void* p)
{ …
```

Fix memory over-write in pipe.hpp

---

include/boost/process/detail/child_decl.hpp

Currently affects the MSVC CI
* boost\include\boost/process/child.hpp(35): error C2600:
'boost::process::child::child': cannot define a compiler-generated
special member function (must be declared in the class first)
* Introduced by 8541cae
* See boostorg/process#113

[Build Fix] Workaround for a MSVC 14.1 and 14.2 compiler bug

---

include/boost/process/async.hpp

The description already states that an io_context needs to be passed. This change is adjusting the example accordingly.

Pass io_context in on_exit example

---

include/boost/process/detail/windows/file_descriptor.hpp

I caught this while compiling with clang 10.0.0 with `-Werror,-Wreturn-type`. I'm unsure if the lack of a return statement was intentional

Added return *this in move assignment operator

---

include/boost/process/detail/posix/executor.hpp

This commit fixes issue #121  (skipping "PATH=" prefix prior to use a PATH string which represents the array of paths separated by semicolons)

Adding bug fix to resolve issue #121

---

include/boost/process/detail/windows/handle_workaround.hpp
include/boost/process/detail/windows/handles.hpp

Removed __kernel_entry usage from Nt* function typedefs, is is part of SAL annoations, not neccessary for proper signature and calling convention
Replaced global DWORD with ::boost::winapi::DWORD_
Also should fix #96 (not verified, I use msvc, not mingw but error appears on the same line)

Fix windows builds that don't include Windows.h

---

include/boost/process/locale.hpp

The comment here is incorrect; an empty locale is not the correct
behavior here and will cause exceptions to be thrown in other code.
Instead a locale object with the default constructor should be
returned, not one created with an empty string. This is a known issue
which was originally reported here:
https://svn.boost.org/trac10/ticket/4688
The issue claims to have been fixed in 7bb19f9 (see also:
https://svn.boost.org/trac10/changeset/72855).
However, this only fixes the issue for FreeBSD and not other POSIX
platforms. This patch is based on the one originally submitted here:
https://svn.boost.org/trac10/attachment/ticket/4688/boost_filesystem.patch

Return default locale on POSIX systems

---

include/boost/process/extend.hpp

`extend.hpp` uses `std::shared_ptr` as a member of `posix_executor` but does not include it.

Add include to extend.hpp for memory.

---

doc/Jamfile.jam

The current Jamfile is counting on the git layout instead of the boost release layout to generate the documentation. We can check the links are now correct for the release layout with `b2 libs/process/doc` from the boost root directory. This PR adjusts the documentation Jamfile with a `path-constant` for the doxygen command. 
This is circumstantially not very problematic at many places in the documentation because the b2 glob command interprets paths relative to the Jamfile (see https://github.com/boostorg/utility/pull/86#issuecomment-989294010), but that's not the case for all commands in there. For instance, the links on the headers like "Header <boost/process/child.hpp>" in the current [reference page](https://www.boost.org/doc/libs/1_78_0/doc/html/process/reference.html) are broken. …

Adjust documentation relative paths

---

include/boost/process/env.hpp

See also: https://stackoverflow.com/questions/58147787/boostprocessenv-broken-on-ubuntu-19-04

Fix missing include

---

CMakeLists.txt

The find_package is not required, as the dependencies are done using the superproject build
The include_directories is already there: target_include_directories
Partial revert of 610b337fa3bc82ecd19cd7baa6e90874f62c050f in #250

Remove superflous calls in CMakeLists

---

.drone.star

After installing compilers on the FreeBSD machines, add linkflags so the toolchain "finds appropriate versions
of the necessary run-time libraries"

Drone: update freebsd jobs

---

include/boost/process/detail/config.hpp

Using boost::throw_exception allows for modifications to these exceptions on a per-application basis, including overriding with custom implementations.
This also has the benefit of allowing compilation with -fno-exceptions set, which should make this code more portable.

Use boost::throw_exception rather than direct throw

---

doc/concepts.qbk

Trivial change: An external URL in this documentation is prefixed by a `(`, which breaks the link
As seen on `https://www.boost.org/doc/libs/1_82_0/doc/html/boost_process/concepts.html`, the link points erroneously to `https://www.boost.org/doc/libs/1_82_0/doc/html/boost_process/(http:/pubs.opengroup.org/onlinepubs/009695399/functions/mkfifo.html`.

Fix typo that breaks link in doc

---

include/boost/process/pipe.hpp

Warning
```
1>StartProcess.cpp
1>C:\Program Files\boost_1_83_0\boost/process/pipe.hpp(132,5): warning C4297: 'boost::process::basic_pipebuf<char,std::char_traits<char>>::~basic_pipebuf': function assumed not to throw an exception but does
1>C:\Program Files\boost_1_83_0\boost/process/pipe.hpp(132,5): message : destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>C:\Program Files\boost_1_83_0\boost/process/pipe.hpp(124,6): message : while compiling class template member function 'boost::process::basic_pipebuf<char,std::char_traits<char>>::~basic_pipebuf(void)'
1>C:\Program Files\boost_1_83_0\boost/process/pipe.hpp(304,42): message : see reference to class template instantiation 'boost::process::basic_pipebuf<char,std::char_traits<char>>' being compiled …
```

Silence compile warning on msvc

---

.drone/drone.bat
include/boost/process/v2/detail/process_handle_windows.hpp
include/boost/process/v2/environment.hpp
include/boost/process/v2/execute.hpp
include/boost/process/v2/ext/impl/cmd.ipp
include/boost/process/v2/windows/creation_flags.hpp
test/v2/environment.cpp
test/v2/pid.cpp
test/v2/process.cpp
test/v2/target.cpp
test/v2/windows.cpp

fixed executor reset_cancellation_state.

---

doc/design.qbk
doc/tutorial.qbk
doc/v2/env.qbk
doc/v2/quickstart.qbk

@klemens-morgenstern , please recheck the [Subprocess environment](https://www.boost.org/doc/libs/1_83_0/doc/html/boost_process/v2.html#boost_process.v2.env.process_env) example again.
Looks like rows `process proc(ctx, exe, {"main.cpp"}, process_environment(my_env));` row still may not be compiled.

Code typos fixes

---

test/CMakeLists.txt

Ran into this error in a CMake build of the Git source with `-DBUILD_TESTING=ON`:
```
[ 46%] Building CXX object libs/process/test/CMakeFiles/boost_process_group_wait.dir/group_wait.cpp.o
In file included from /tmp/boost/libs/system/include/boost/system/error_category.hpp(11),
from /tmp/boost/libs/system/include/boost/system/error_code.hpp(14),
from /tmp/boost/libs/process/test/group_wait.cpp(15):
/tmp/boost/libs/system/include/boost/system/detail/error_category_impl.hpp(141): warning #2196: routine is both "inline" and "noinline"
inline BOOST_NOINLINE error_category::operator std::error_category const & () const
^
/tmp/boost/libs/process/test/group_wait.cpp(19): catastrophic error: cannot open source file "/tmp/boost/libs/process/test/group_wait.cpp"
#include <boost/scope_exit.hpp>
^ …
```

fix group_wait test in cmake build.

---

include/boost/process/v2/ext/impl/cwd.ipp
include/boost/process/v2/ext/impl/exe.ipp

filesystem::canonical is basically the same thing as realpath on Unix-likes, which only resolves one symbolic link. If one symbolic link points to yet another symbolic link and so on and so forth, it will not resolve all symbolic links. It will only do one link for each call to canonical. On SunOS, unlike Linux, /proc/${pid}/cwd does not directly point to the literal current working directory of the given ${pid}. Instead, it will point to yet another symlink - /proc/${pid}/path/cwd which once you have followed that second link only then will you have the literal cwd path for the process id.

Fix V2::EXT::CWD [SunOS]

---

include/boost/process/detail/posix/pipe_out.hpp

In commit cbaa913e3d73 ("Merge branch 'develop' into limit_fd"), there have been merge conflicts in two files. In pipe_out.hpp, a previous commit from the "limit_fd" branch f8c0dd4da58a ("prototype for limit_fd") had been eliminated during wrong conflict resolution.
The final result was, that file descriptors for stdout pipes were not preserved when using limit_handles.
Example:
boost::asio::io_context io_context;
bp::async_pipe my_stdin(io_context);
bp::async_pipe my_stdout(io_context);
bp::child my_child("/usr/bin/echo", "Hello world",
bp::std_in  < my_stdin,  // preserved by limit_handles
bp::std_out > my_stdout, // closed by limit_handles
bp::std_err > stderr,    // preserved by limit_handles
bp::limit_handles)
Fixes: cbaa913e3d73 ("Merge branch 'develop' into limit_fd")

posix: pipe_out: fix merge conflict

---

include/boost/process/detail/windows/environment.hpp

Issue description: for Windows using MSVC when get method is invoked using native_environment_impl<Char=wchar_t> object compilation error C2440 (conversion from const char[] to std::wstring) is invoked
Reproduction: https://godbolt.org/z/4rMbzPKE5
Proposed solution: change of return value to empty std::basic_string<Char> object

native_environment_impl::get method bugfix for Windows wchar_t

---

include/boost/process/v2/execute.hpp

When `async_execute` is called on a process, the process is moved into a unique pointer and then the executor is called on the moved from process. This causes warnings from many static analyzers and compilers.
Although in this case I don't believe this is a bug, since it appears that the executor is being copied (from what I can tell), it may be a good idea to simply call this method on the new object.

Fix call on moved variable in execute

---

include/boost/process/v2/exit_code.hpp

The initial value for the exit_code (0x7f) in v2 doesn't work with musl libc. Here WIFSIGNALED(0x7f) expands to a non-zero value:
http://git.musl-libc.org/cgit/musl/tree/include/sys/wait.h#n54

v2: sync initial value for exit code with v1

---

include/boost/process/v2/ext/impl/cmd.ipp
include/boost/process/v2/ext/impl/cwd.ipp
include/boost/process/v2/ext/impl/env.ipp

On FreeBSD I would like to remove dependency on libprocstat completely, and replace it with libkvm to be more like the other *BSD platforms in terms of linker dependencies. This pull request is our first move in that direction.

Less dependency on libprocstat and various corrections.

---

include/boost/process/detail/posix/executor.hpp
test/limit_fd.cpp

Hi,
This pull request contains a fix for posix `limit_handles`: It looks like `_pipe_sink` (the internal pipe used for passing exec() errors from child to parent) must be assigned earlier, before `call_on_setup()` and `limit_fd_::on_setup()`, so `executor::get_used_handles()` can see it. Otherwise it will be closed when using `limit_handles`, despite commit 1a1d677d which added the `executor::get_used_handles()`.

posix: Fix exec error reporting with limit_handles

---

include/boost/process/detail/posix/pipe_out.hpp
test/posix_specific.cpp

Hi,
This pull request re-adds a close() call in posix pipe_out, which already existed before commit caa7b2fcc8. pipe_out should always close its fd for the read end of the pipe. It already did it when redirecting only stdout or only stderr, but it was missing for the third case where both stdout and stderr are redirected (`bp::std_out & bp::std_err > my_async_pipe`).
The second commit adds a unit test for this issue, hopefully it is useful, although I'm not sure if this style of test is okay.

posix: Fix pipe fd leak if redirecting both stdout and stderr

---

build/Jamfile

else it can fail to link on mingw:
```
process_handle_windows.o:process_handle_windows.cpp:(.text+0x25): undefined reference to `_imp__WSACleanup@0'
```
/cc @klemens-morgenstern

Fix undefined reference to ws2_32

---

include/boost/process/v2/posix/default_launcher.hpp
src/pid.cpp
src/posix/close_handles.cpp

OpenBSD does not have close_range() nor does NetBSD.
OpenBSD needs environ like the other *BSD's.
The build was erroring on kp_pid, it looks like p_pid is appropriate.
Fixes: https://github.com/boostorg/process/issues/391

Fix building on OpenBSD

---

src/ext/cwd.cpp

Using an additional `sysctl()` call to predetermine the length of the buffer always returns a length of zero due to an OS-level bug, so we are forced to use a fixed-length buffer instead, which doesn't dynamically resize to the necessary size to fit buffer contents.

[DragonFly BSD] Correct CWD from PID Code.

---

include/boost/process/v2/stdio.hpp
include/boost/process/v2/windows/as_user_launcher.hpp
include/boost/process/v2/windows/default_launcher.hpp
src/windows/default_launcher.cpp

thanks @NVCherney for bring this to my attention.

v2 uses PROC_THREAD_ATTRIBUTE_HANDLE_LIST for limiting fd

---

include/boost/process/v2/stdio.hpp
test/v2/process.cpp

Fixes #448. Aside from adding the move operations, I've also added two test cases: one demonstrating implicit creation of pipes by `process_stdio` which was previously untested AFAICT, and one (regression) test specifically for the move semantics.
I'm curious if you'd also be open to making the members for `process_io_binding` private (on both platforms, actually)? `process_io_binding` has to maintain an invariant (whether `fd` needs to be closed) and leaving its members public allows external code to break that invariant. I'm not sure that your policy is towards breaking source compatibility in the `detail` namespace, so I have refrained from making that change.

Fix POSIX `process_stdio` move semantics

---

include/boost/process/posix/bind_fd.hpp
include/boost/process/posix/default_launcher.hpp
include/boost/process/posix/fork_and_forget_launcher.hpp
include/boost/process/posix/pdfork_launcher.hpp
include/boost/process/posix/vfork_launcher.hpp

I tried to use some other launcher on Linux, but compilation was failing due to the wrong include paths.
(There may be more wrong paths that I haven't noticed, so please feel free to reject this pull request and make the fixes as you wish. I could have opened up an issue instead, but felt this is fine too.)

Fix include directives from boost/process/posix/*.hpp having wrong paths

---

CMakeLists.txt

Build previously failed when BOOST_PROCESS_USE_STD_FS was ON, because filesystem was linked to regardless.
I tried to use this library with the std version of filesystem and I noticed that Boost::filesystem was listed as a dependency regardless of the flag. I'm pretty sure this is just a little mistake.

Remove optional dependency on filesystem when not meant to be

---

include/boost/process/v2/detail/environment_win.hpp

The destinations should point to the *end* of the destination range
https://en.cppreference.com/w/cpp/algorithm/move_backward

Fix up usage of `std::move_backward`

---

include/boost/process/v1/detail/windows/async_pipe.hpp

Include numerical representation of local static variable's address into the pipe name to discriminate Boost.Process instances in independent DLLs.
Fixes #476

Fix conflicting pipe name in independent plug-in DLLs that is causing error 231: All pipe instances are busy 

---

include/boost/process/v1/locale.hpp

This commit effectively reverts #179 which shouldn't have been merged in the first place. See https://github.com/boostorg/filesystem/pull/163#issuecomment-786794483 for explanation.
For example, this code https://godbolt.org/z/rdvxh1EPz throws the following exception:
```c++
boost::process codecvt to char: error
```
Workaround is to manually call `boost::process::imbue` with the correct locale:
```c++
boost::process::imbue(std::locale(""));
```

Fix wide strings conversion on POSIX

---

.github/workflows/ci.yml

The Ubuntu 20.04 image on GitHub Actions has been unavailable since 2025-04-15. See <https://github.com/actions/runner-images/issues/11101> for more information on the deprecation and removal.
Therefore all build jobs that use the Ubuntu 20.04 runner image of GHA will fail and have to be replaced by newer images or have to move into Ubuntu 20.04 containers.

Remove Ubuntu 20.04 builds from CI

---

doc/reference/environment.adoc
doc/version2.adoc
include/boost/process/v1/async.hpp
include/boost/process/v1/async_pipe.hpp
include/boost/process/v1/child.hpp
include/boost/process/v2/environment.hpp
test/v2/target.cpp

Fix some typos, no functional changes.

Fix some typos

---

src/pid.cpp

Needs testing...
Edit:
Has been tested on my end. Seems to work.

Support child_pids() Even When PROC_PPID_ONLY is Undefined on Mac
